### ISSUE TITLE
Events not firing on Meteor 1.1

### ISSUE THREAD

**Issue by aendrew** [chriswessels/meteor-hammer#14]
I have no idea what I'm doing wrong. First I'm installing via `meteor add chriswessels:hammer`, then I have this in my controller:

```
Template.Participate.gestures({
  'tap .card': function(e, tem) {
    alert('this does not work');
  }
});

Template.Participate.events({
  'click .card': function(e, tem) {
    console.log('this does, however, work');
  }
});
```

Any idea what's preventing the tap event from firing? Doesn't matter what event, same goes with swipe and pinch, etc. Using 3.1.0 on Meteor 1.1 (via Iron CLI).

**Comment by aacase** [comment]
I've experienced this too, however, the event will fire the first time the template loads, but on reroute, will not work.

**Comment by patrickml** [comment]
I am having this issue as well, however I am having it on meteor 1.0.4 I am now updating to 1.1 and will edit this post if the issue persists

**Comment by ppryde** [comment]
Ditto :( nought on 1.1

**Comment by chriswessels** [comment]
Thanks all, I'll take a look at this as soon as I have a moment.

**Comment by chriswessels** [comment]
Hey guys,

I updated my test application to Meteor 1.1.0.2 and everything still works, so I'm not sure what's going wrong for you. Nevertheless, I've released chriswessels:hammer@3.1.1 on Atmosphere, which updates the package dependencies.

Let me know if this works. If it doesn't, it would be good to have steps to reproduce or access to an app where it isn't working.

Thanks,
Chris

**Comment by chriswessels** [comment]
@patrickml @aendrew @aacase Are you still experiencing this issue?

**Comment by patrickml** [comment]
I haven’t had time to check as I have been on vacation. I will reply to the thread once I get back.


Thank you,

Patrick Lewis
Lead Developer
Revolt Visual
828.461.6433
revoltvisual.com <http://revoltvisual.com/>

**Comment by jaskinn** [comment]
I have just installed this and I am experiencing the same issue. @chriswessels Would it be possible to have a look at your test application. I believe that I must be doing something basic wrong.

**Comment by egorvinogradov** [comment]
Doesn't work for me as well

**Comment by bignimbus** [comment]
+1 just installed, hammer events not firing.

**Comment by plraphael** [comment]
Having the same issue here...

**Comment by chriswessels** [comment]
Hey all,

Thanks for the reports and for being patient.

As I'd like the plugin to be as ideally structured as possible, I've opened a discussion asking for guidance here: https://forums.meteor.com/t/guidance-needed-for-chriswessels-hammer-hammer-js-blaze-integration/3532

Hopefully we'll have a solution soon!

Chris

**Comment by bitdepth** [comment]
So I also have an issue with events not firing, i think the gestures are being bound before the elements are rendered by the template. If i manually re-bind the events after the page has loaded everything works fine. Any ideas?
$('#swipe-test').hammer().bind("swipeleft", function(){
console.log('swipeleft worked')
});

**Comment by chriswessels** [comment]
@bitdepth You're using Hammer via the jQuery plugin (bundled) which is susceptible to Blaze overwrites which is why you're getting this behaviour. Try using the `Template.foo.gestures` API provided by this smart package, or try moving your code into a `Template.foo.onRendered` callback.

If you have further questions unrelated to this thread, please open a new issue.

**Comment by bitdepth** [comment]
@chriswessels thank's for the response. It's possible i didn't explan things very well in my last post. I do have things setup using the API you provided. Code shown below. What i was trying to say was that when i was debugging i realised that if i called the the hammer.bind function manually from the console i could at least get the events firing. I've since read your post  https://forums.meteor.com/t/guidance-needed-for-chriswessels-hammer-hammer-js-blaze-integration/3532 so i am more aware of the issues.

```javascript
Template.teamPage.rendered = function(){
  $('body').data('hammer').set({
    drag_min_distance:1,
    swipe_velocity:0.1
  });
};

Template.teamPage.gestures({
  'swipeleft .item-content': function(event) {
    console.log("Swipe success!");
  }
});
```

**Comment by chriswessels** [comment]
I discuss a few solutions here: https://forums.meteor.com/t/guidance-needed-for-chriswessels-hammer-hammer-js-blaze-integration/3532/4

Any feedback would be appreciated.

**Comment by bignimbus** [comment]
I think number 3 is a nice solution.

**Comment by chriswessels** [comment]
Thanks for the feedback @bignimbus. I agree.

I'm writing an API proposal, hopefully I'll get it done in the next few days and then it would be good to get community feedback.

**Comment by chriswessels** [comment]
Hey everyone,

I've published 4.0.0-rc1 on Atmosphere. You can test it by running:

    $ meteor add chriswessels:hammer@4.0.0-rc1

The new API is not backwards compatible. I need to write new documentation, but this should be enough to get you going: https://github.com/chriswessels/meteor-hammer/blob/rewrite/API.md

I apologise for the changes, but I'm happy with this new approach. It feels way less hacky than before.

Simple example of new API:

```html
<template name="simple">
  {{#HammerTouchArea gestureMap=templateGestures}}
    <ul>
    {{#each someArray}}
      <li>
        {{someField}}
      </li>
    {{/each}}
    </ul>
  {{/HammerTouchArea}}
</template>
```

```javascript
Template.simple.helpers({
  templateGestures: {
    'doubletap ul li': function (event, templateInstance) {
      /* `event` is the Hammer.js event object */
      /* `templateInstance` is the `Blaze.TemplateInstance` */
      /* `this` is the data context of the element in your template, so in this case someField from someArray */
    }
  }
});
```

The new API also provides a callback for configuring the Hammer instance as you'd like. It also allows you to specify initialisation options for Hammer (which let you set things like cssProps, which could previously not be done).

If I get the thumbs up from all of you, I'll write more comprehensive docs and publish 4.0.0 as a major release on Atmosphere.

Cheers,
Chris

**Comment by chriswessels** [comment]
Pushed an updated README for the slated `4.0.0` release. The docs are not complete yet, but for those who are interested: https://github.com/chriswessels/meteor-hammer/blob/rewrite/README.md

You can test this functionality with `$ meteor add chriswessels:hammer@4.0.0-rc1`.

Chris

**Comment by chriswessels** [comment]
Hey all,

`4.0.0` released on Atmosphere with new API.

Please see [README.md](https://github.com/chriswessels/meteor-hammer/blob/master/README.md) and [MIGRATION.md](https://github.com/chriswessels/meteor-hammer/blob/master/MIGRATION.md).

Chris

**Comment by mj12albert** [comment]
I'm still experiencing this issue with `4.0.1` and Meteor 1.1.0.2 – 'tap .class' doesn’t work, but 'tap #id' works just fine.

**Comment by chriswessels** [comment]
@mj12albert Please could you provide an example or simple steps to reproduce.

**Comment by mj12albert** [comment]
Actually, I got around this by removing `ev.preventDefault()` from a `'tap .class': function(){...}`.

Weirdly enough `'tap #id': function(ev) {ev.preventDefault(); //do other stuff}` works fine.

But I can't reproduce this at all in a new meteor project I set up to debug this...
